// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RivenBackend.Data;

#nullable disable

namespace RivenBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RivenBackend.Models.AiReport", b =>
                {
                    b.Property<int>("AiReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AiReportId"));

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("text");

                    b.Property<string>("AfDetectionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<string>("CtScanResult")
                        .HasColumnType("text");

                    b.Property<string>("EcgImageResult")
                        .HasColumnType("text");

                    b.Property<string>("EcgSignalResult")
                        .HasColumnType("text");

                    b.Property<DateTime>("GenerationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NihssScore")
                        .HasColumnType("text");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("text");

                    b.Property<string>("StrokeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.HasKey("AiReportId");

                    b.HasIndex("CaseId")
                        .IsUnique();

                    b.ToTable("AiReports");
                });

            modelBuilder.Entity("RivenBackend.Models.Ambulance", b =>
                {
                    b.Property<int>("AmbulanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmbulanceId"));

                    b.Property<string>("AmbulanceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<double?>("CurrentLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("CurrentLongitude")
                        .HasColumnType("float");

                    b.Property<double?>("DistanceMiles")
                        .HasColumnType("float");

                    b.Property<int?>("EtaMinutes")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("text");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("text");

                    b.HasKey("AmbulanceId");

                    b.HasIndex("HospitalId");

                    b.ToTable("Ambulances");
                });

            modelBuilder.Entity("RivenBackend.Models.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(100)
                        .HasColumnType("text");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AttachmentId");

                    b.HasIndex("CaseId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("RivenBackend.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("RivenBackend.Models.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseId"));

                    b.Property<int>("AmbulanceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArrivedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HandoverNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("HandoverTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text");

                    b.Property<double?>("LocationLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("LocationLongitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("OnsetTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientConditionOnArrival")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ReceivingPhysician")
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CaseId");

                    b.HasIndex("AmbulanceId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UserId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("RivenBackend.Models.EcgResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("EcgResults");
                });

            modelBuilder.Entity("RivenBackend.Models.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text");

                    b.Property<int>("AvailableStrokeBeds")
                        .HasColumnType("int");

                    b.Property<string>("CityStateZip")
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("text");

                    b.Property<bool>("EmergencyBayCleared")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text");

                    b.Property<bool>("NeurologistOnStandby")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("text");

                    b.Property<string>("StrokeCenterType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<bool>("StrokeTeamNotified")
                        .HasColumnType("bit");

                    b.Property<int>("WaitTimeMinutes")
                        .HasColumnType("int");

                    b.HasKey("HospitalId");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("RivenBackend.Models.Medication", b =>
                {
                    b.Property<int>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicationId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text");

                    b.HasKey("MedicationId");

                    b.HasIndex("CaseId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("RivenBackend.Models.NihssAssessment", b =>
                {
                    b.Property<int>("NihssId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NihssId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("DomainScores")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<string>("SeverityLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("NihssId");

                    b.HasIndex("CaseId")
                        .IsUnique();

                    b.ToTable("NihssAssessments");
                });

            modelBuilder.Entity("RivenBackend.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(200)
                        .HasColumnType("text");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("CaseId");

                    b.HasIndex("HospitalId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("RivenBackend.Models.OtpVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("RivenBackend.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("RivenBackend.Models.RiskFactors", b =>
                {
                    b.Property<int>("RiskFactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RiskFactorId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<bool>("Diabetes")
                        .HasColumnType("bit");

                    b.Property<bool>("HeartDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("HighCholesterol")
                        .HasColumnType("bit");

                    b.Property<bool>("Hypertension")
                        .HasColumnType("bit");

                    b.Property<bool>("Obesity")
                        .HasColumnType("bit");

                    b.Property<bool>("PhysicalInactive")
                        .HasColumnType("bit");

                    b.Property<bool>("PreviousStroke")
                        .HasColumnType("bit");

                    b.Property<bool>("SleepApnea")
                        .HasColumnType("bit");

                    b.Property<bool>("Smoking")
                        .HasColumnType("bit");

                    b.HasKey("RiskFactorId");

                    b.HasIndex("CaseId")
                        .IsUnique();

                    b.ToTable("RiskFactors");
                });

            modelBuilder.Entity("RivenBackend.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RivenBackend.Models.StrokeResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalImagesProcessed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StrokeResults");
                });

            modelBuilder.Entity("RivenBackend.Models.Symptoms", b =>
                {
                    b.Property<int>("SymptomsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SymptomsId"));

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("text");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedSymptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SymptomsId");

                    b.HasIndex("CaseId")
                        .IsUnique();

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("RivenBackend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("AccountCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RivenBackend.Models.VitalSigns", b =>
                {
                    b.Property<int>("VitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VitalId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int>("DiastolicBP")
                        .HasColumnType("int");

                    b.Property<double>("GlucoseLevel")
                        .HasColumnType("float");

                    b.Property<double>("HeartRate")
                        .HasColumnType("float");

                    b.Property<double>("RespiratoryRate")
                        .HasColumnType("float");

                    b.Property<double>("SpO2")
                        .HasColumnType("float");

                    b.Property<int>("SystolicBP")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<string>("TemperatureUnit")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("text");

                    b.HasKey("VitalId");

                    b.HasIndex("CaseId")
                        .IsUnique();

                    b.ToTable("VitalSigns");
                });

            modelBuilder.Entity("RivenBackend.Models.AiReport", b =>
                {
                    b.HasOne("RivenBackend.Models.Case", "Case")
                        .WithOne("AiReport")
                        .HasForeignKey("RivenBackend.Models.AiReport", "CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("RivenBackend.Models.Ambulance", b =>
                {
                    b.HasOne("RivenBackend.Models.Hospital", "Hospital")
                        .WithMany("Ambulances")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("RivenBackend.Models.Attachment", b =>
                {
                    b.HasOne("RivenBackend.Models.Case", "Case")
                        .WithMany("Attachments")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("RivenBackend.Models.AuditLog", b =>
                {
                    b.HasOne("RivenBackend.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RivenBackend.Models.Case", b =>
                {
                    b.HasOne("RivenBackend.Models.Ambulance", "Ambulance")
                        .WithMany("Cases")
                        .HasForeignKey("AmbulanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RivenBackend.Models.Hospital", "Hospital")
                        .WithMany("Cases")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RivenBackend.Models.Patient", "Patient")
                        .WithMany("Cases")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RivenBackend.Models.User", "User")
                        .WithMany("Cases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ambulance");

                    b.Navigation("Hospital");

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RivenBackend.Models.EcgResult", b =>
                {
                    b.HasOne("RivenBackend.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("RivenBackend.Models.Medication", b =>
                {
                    b.HasOne("RivenBackend.Models.Case", "Case")
                        .WithMany("Medications")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("RivenBackend.Models.NihssAssessment", b =>
                {
                    b.HasOne("RivenBackend.Models.Case", "Case")
                        .WithOne("NihssAssessment")
                        .HasForeignKey("RivenBackend.Models.NihssAssessment", "CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("RivenBackend.Models.Notification", b =>
                {
                    b.HasOne("RivenBackend.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RivenBackend.Models.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("RivenBackend.Models.RiskFactors", b =>
                {
                    b.HasOne("RivenBackend.Models.Case", "Case")
                        .WithOne("RiskFactors")
                        .HasForeignKey("RivenBackend.Models.RiskFactors", "CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("RivenBackend.Models.Symptoms", b =>
                {
                    b.HasOne("RivenBackend.Models.Case", "Case")
                        .WithOne("Symptoms")
                        .HasForeignKey("RivenBackend.Models.Symptoms", "CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("RivenBackend.Models.User", b =>
                {
                    b.HasOne("RivenBackend.Models.Hospital", "Hospital")
                        .WithMany("Users")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RivenBackend.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hospital");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RivenBackend.Models.VitalSigns", b =>
                {
                    b.HasOne("RivenBackend.Models.Case", "Case")
                        .WithOne("VitalSigns")
                        .HasForeignKey("RivenBackend.Models.VitalSigns", "CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("RivenBackend.Models.Ambulance", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("RivenBackend.Models.Case", b =>
                {
                    b.Navigation("AiReport");

                    b.Navigation("Attachments");

                    b.Navigation("Medications");

                    b.Navigation("NihssAssessment");

                    b.Navigation("RiskFactors");

                    b.Navigation("Symptoms");

                    b.Navigation("VitalSigns");
                });

            modelBuilder.Entity("RivenBackend.Models.Hospital", b =>
                {
                    b.Navigation("Ambulances");

                    b.Navigation("Cases");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RivenBackend.Models.Patient", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("RivenBackend.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RivenBackend.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
